### ISSUE TITLE
使用命令”订阅列表“，提示”错误码: -403, 信息: 访问权限不足“

### ISSUE THREAD

**Issue by cj1357** [zangxx66/nonebot_plugin_blive_danmaku#11]
![image](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/40661342/b5b70197-705a-46a5-8bd7-cc2bcb6812a3)

报错代码：
06-23 21:44:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_blive_danmaku.command.sub.sub_list)
06-23 21:44:39 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_blive_danmaku.command.sub.sub_list) running complete
06-23 21:44:39 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_blive_danmaku.command.sub.sub_list) failed.
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 24, in <module>
    nonebot.run()
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot_plugin_blive_danmaku/command/sub/sub_list.py", line 21, in _
    user = await get_user_info(sub.uid, reqtype="web", proxies=None)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/bilireq/user/__init__.py", line 12, in get_user_info
    return await get(url, params=params, auth=auth, reqtype=reqtype, **kwargs)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/bilireq/utils/__init__.py", line 98, in get
    return await request("GET", url, **kwargs)
  File "/home/poetry-cache/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/bilireq/utils/__init__.py", line 89, in request
    raise ResponseCodeError(
bilireq.exceptions.ResponseCodeError: 错误码: -403, 信息: 访问权限不足

**Comment by zangxx66** [comment]
B站那边的报错，应该是添加了新的参数做校验

**Comment by zangxx66** [comment]
新版本已更新依赖

**Comment by cj1357** [comment]
没问题了😺
