### ISSUE TITLE
Bug?：开启路灯后报错  >>>

### ISSUE THREAD

**Issue by Oranges4001** [zangxx66/nonebot_plugin_blive_danmaku#12]
room=21452505 _handle_command() failed, command={'cmd': 'DANMU_MSG', 'info': [[0, 1, 25, 5816798, 1688413880504, 1688411487, 0, 'd332ad00', 0, 0, 0, '', 0, '{}', '{}', {'mode': 0, 'show_player_type': 0, 'extra': '{"send_from_me":false,"mode":0,"color":5816798,"dm_type":0,"font_size":25,"player_mode":1,"show_player_type":0,"content":"8888","user_hash":"3543313664","emoticon_unique":"","bulge_display":0,"recommend_score":1,"main_state_dm_color":"","objective_state_dm_color":"","direction":0,"pk_direction":0,"quartet_direction":0,"anniversary_crowd":0,"yeah_space_type":"","yeah_space_url":"","jump_to_url":"","space_type":"","space_url":"","animation":{},"emots":null,"is_audited":false,"id_str":"0481be3d673828ceae59ea2da4cd7a3411","icon":null}'}, {'activity_identity': '', 'activity_source': 0, 'not_show': 0}, 0], '8888', [0, '濑***', 0, 0, 0, 10000, 1, ''], [18, '脆鲨', '七海Nana7mi', 21452505, 13081892, '', 0, 13081892, 13081892, 13081892, 0, 1, 434334701], [10, 0, 9868950, '>50000', 0], ['', ''], 0, 0, None, {'ts': 1688413880, 'ct': '11ED4B71'}, 0, 0, None, None, 0, 63, [0]], 'dm_v2': 'CiIwNDgxYmUzZDY3MzgyOGNlYWU1OWVhMmRhNGNkN2EzNDExEAEYGSDeg+MCKghkMzMyYWQwMDIEODg4ODi4gb3qkTFI37qMpQZiAIoBAJoBEAoIMTFFRDRCNzEQuM2MpQaiAZIBEgbmv5EqKioiSmh0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9mYWNlL2NiMDY1M2E4N2IxYTNjMGFmZjllYzY0MmJiNjIzNTdkZmZlMTcwNTEuanBnOJBOQAFaIAgSEgbohIbpsqggpLqeBjCkup4GOKS6ngZApLqeBlABYg8IChCWrdoEGgY+NTAwMDBqAHIAegCqARoI7deNzwESDeS4g+a1t05hbmE3bWkY2a2dCg=='}
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\blivedm\blivedm\handlers.py", line 164, in handle
    await callback(self, client, command)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\command\subscribe\danmaku.py", line 73, in _on_danmaku
    await save_danmaku(client.room_id, client.room_owner_uid, message.uname, int(message.timestamp / 1000), message.msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\command\subscribe\danmaku.py", line 138, in save_danmaku
    room = room_list[0]
IndexError: list index out of range
![error log](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/fd4f10fd-6dd0-420b-a02a-87e3143ef037)

**Comment by zangxx66** [comment]
日志`xx开播了，连接直播间`前后是否有其他报错

**Comment by Oranges4001** [comment]
07-04 22:06:18 [INFO] nonebot_plugin_blive_danmaku | 七海Nana7mi开播了，连接直播间
07-04 22:06:18 [ERROR] apscheduler | Job "danmaku (trigger: interval[0:00:15], next run at: 2023-07-04 22:06:32 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 117, in execute_insert
    return (await connection.execute_insert(query, values))[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 194, in execute_insert
    return await self._execute(self._execute_insert, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 74, in _execute_insert
    cursor = self._conn.execute(sql, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: liveroom.watch_person

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Bot\1_bot_nonebot\nb2\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\command\subscribe\danmaku.py", line 66, in danmaku
    await db.add_room(room_id=room_id, uid=uid, cover=cover, title=info["title"], name=info["uname"], start_time=start_timespan, end_time=0)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\database\db.py", line 140, in add_room
    res = await LiveRoom.add(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\database\model.py", line 23, in add
    await cls.create(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\models.py", line 1139, in create
    await instance.save(using_db=db, force_create=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\models.py", line 943, in save
    await executor.execute_insert(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\base\executor.py", line 227, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 38, in translate_exceptions_
    raise IntegrityError(exc)
tortoise.exceptions.IntegrityError: NOT NULL constraint failed: liveroom.watch_person
![error-log-1](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/9ef95908-c833-48b7-af04-0b801f75134a)
![error-log-2](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/29599c6f-a09d-48b9-b2a2-40e5421dfb09)
![error-log-3](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/8c15bef2-9b4c-489c-ae5a-4361cc6f40ba)

**Comment by Oranges4001** [comment]
> 日志`xx开播了，连接直播间`前后是否有其他报错
有的

07-04 22:06:18 [INFO] nonebot_plugin_blive_danmaku | 七海Nana7mi开播了，连接直播间
07-04 22:06:18 [ERROR] apscheduler | Job "danmaku (trigger: interval[0:00:15], next run at: 2023-07-04 22:06:32 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 117, in execute_insert
    return (await connection.execute_insert(query, values))[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 194, in execute_insert
    return await self._execute(self._execute_insert, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiosqlite\core.py", line 74, in _execute_insert
    cursor = self._conn.execute(sql, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: liveroom.watch_person

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Bot\1_bot_nonebot\nb2\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\command\subscribe\danmaku.py", line 66, in danmaku
    await db.add_room(room_id=room_id, uid=uid, cover=cover, title=info["title"], name=info["uname"], start_time=start_timespan, end_time=0)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\database\db.py", line 140, in add_room
    res = await LiveRoom.add(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_blive_danmaku\database\model.py", line 23, in add
    await cls.create(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\models.py", line 1139, in create
    await instance.save(using_db=db, force_create=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\models.py", line 943, in save
    await executor.execute_insert(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\base\executor.py", line 227, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\backends\sqlite\client.py", line 38, in translate_exceptions_
    raise IntegrityError(exc)
tortoise.exceptions.IntegrityError: NOT NULL constraint failed: liveroom.watch_person
![error-log-1](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/9ef95908-c833-48b7-af04-0b801f75134a)
![error-log-2](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/29599c6f-a09d-48b9-b2a2-40e5421dfb09)
![error-log-3](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/105551172/8c15bef2-9b4c-489c-ae5a-4361cc6f40ba)
