### ISSUE TITLE
运行时出现报错

### ISSUE THREAD

**Issue by RAINighty** [zangxx66/nonebot_plugin_blive_danmaku#17]
```
01-16 00:29:35 [ERROR] nonebot | Error when running startup function. Ignored!
Traceback (most recent call last):
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 153, in execute_script
    async with self.acquire_connection() as connection:
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 220, in __aenter__
    await self.ensure_connection()
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 216, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 69, in create_connection
    await self._connection._connect()
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 137, in _connect
    self._connection = await future
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 397, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 60, in _serve
    await self._startup()
> File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 68, in _startup
    await self._lifespan.startup()
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 41, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 35, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/nonebot_plugin_blive_danmaku/database/db.py", line 28, in init
    await Tortoise.generate_schemas()  # type:ignore
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/__init__.py", line 640, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/utils.py", line 31, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/base/schema_generator.py", line 448, in generate_from_string
    await self.client.execute_script(creation_string)
  File "/root/livepushfortest/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: unable to open database file

```

**Comment by zangxx66** [comment]
你好 @RAINighty，我已收到你的issue，问题有新的进展或疑问我会及时回复你。

**Comment by RAINighty** [comment]
问题依然存在

**Comment by zangxx66** [comment]
请确认程序运行后是否在程序目录下有/data/danmakuBot.sqlite3文件，确保你对程序目录具有读写权限

**Comment by RAINighty** [comment]
> 请确认程序运行后是否在程序目录下有/data/danmakuBot.sqlite3文件，确保你对程序目录具有读写权限

已解决，但是在添加订阅时`发生未知错误：-352 -> -352，请联系开发者`
根据[TDK1969/nonebot_plugin_bilibilibot Issue#58](https://github.com/TDK1969/nonebot_plugin_bilibilibot/issues/58)，似乎是接口修改？

PS：导入cookie需要什么函数？完整的cookie还是buvid3即可？

**Comment by zangxx66** [comment]
浏览器的cookie就行，缺点是一个账号不能同时登录，不然会失效，而且目前暂没有刷新cookie的方式。  
订阅错误是上游依赖的问题，需要排除解决方案
